<?php var_dump($this->get_all_user_info()); ?>

<div class="container">
    <div class="container-title">Admin Panel</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Go back</a>
        <a href="<?= BASE_PATH; ?>user/index">Users</a>
        <a href="<?= BASE_PATH; ?>user/groups">User groups</a>
        <a href="<?= BASE_PATH; ?>user/roles">User roles</a>
    </div>
</div>