<?php
    $role = !empty( $data ) ? $data : "";
?>

<form action="<?= BASE_PATH ?>roles/delete"
      method="post"
      class="popup-form-form"
      data-url="<?= BASE_PATH ?>roles/get_roles_table_result"
      data-id="delete-<?= $role->id ?>">
    <a href="" class="popup-form-close"></a>
    <h1>Delete system role <?= $role->name ?></h1>
    <fieldset>
        <legend>Please choose an option.</legend>
        <input type="hidden" name="success" value="Role <?= $role->name ?> successfully deleted.">
        <input type="hidden" name="error" value="Something went wrong while deleting this role..">
        <input type="hidden" name="id" value="<?= $role->id ?>">
        <div class="popup-form-section">
            <label for="delete">Are you sure?<span></span></label>
        </div>
        <div class="popup-form-section">
            <input type="submit" name="deleteRoleSubmit" value="Yes" class="popup-form-delete">
            <a href="" class="popup-form-delete-cancel">No</a>
        </div>
    </fieldset>
</form>

