<?php

use app\core\Pagination;

// Limit and page number

$limit                 = ( !empty( $limit ) ? $limit : 12 );
$page                  = ( !empty( $data ) ? $data : 1 );

$total_roles           = $this->get_all_roles()->count();
$roles                 = $this->get_all_roles_paginated( $limit, $page );
$total_roles_paginated = $roles->count();
$total_rows            = $total_roles;

?>

<div class="table-intro">
    <h1>System roles table</h1>
    <p>
        Roles: <?= $total_roles ?>
        <?php if( $total_roles_paginated > $limit ){ ?>
        On this page: <?= $total_roles_paginated ?>
        <?php } ?>
    </p>
</div>

<div class="table">
    <div class="table-row">
        <div class="table-header">Role</div>
        <div class="table-header">Users</div>
        <div class="table-header">Since</div>
        <div class="table-header"></div>
    </div>
    <div class="table-row"></div>
    <?php
    foreach( $roles  as $role ){
        $total_users = $role->users->count();
        echo '<div class="table-row">';
        echo '<div class="table-cell">' . ' (' . $total_users . ') ' . $role->name . '</div>';
        echo '<div class="table-cell">';
        /** Users */
        if( !$role->users->isEmpty() ) {
            echo '<select>';
            foreach ($role->users as $user) {
                echo '<option>' . $user->name . '</option>';
            }
            echo '</select>';
        } else {
            echo '<i>This role has no users</i>';
        }
        echo '</div>';

        echo '<div class="table-cell">' . $role->created_at . '</div>';
        echo '<div class="table-cell">
                <a href="" class="popup-form-link" data-id="' . $role->id . '">Edit</a>
                <a href="' . BASE_PATH . 'roles/delete" 
                   class="popup-form-delete" 
                   data-id="' . $role->id . '" 
                   data-text="Role ' . $role->name . ' is deleted."
                   data-url="' . BASE_PATH . 'roles/get_roles_table_result"
                   >Delete</a>
              </div>';
        echo '</div>';
        echo '<div class="popup-form-container">';
        echo '<div class="popup-form" id="' . $role->id . '">';
            $this->view_partial('roles', 'edit-role', $role);
        echo '</div>';
        echo '</div>';
    }

    ?>
</div>

<?php

// Show the pagination if total rows is bigger then the limit.

if( $total_rows > $limit ) {
    $data_url = 'roles/get_roles_table_result';
    echo ( new Pagination( $total_rows, $limit, $page ) )->createPagination( $data_url );
}