<?php

$page = ( !empty( $data ) ? $data : 1 );

var_dump( $_SESSION['page'] );

?>

<div class="container">
    <div class="container-title">Groups</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Go back</a>
        <a href="" class="popup-form-link" data-id="new-group">New group</a>
    </div>
</div>

<div class="popup-form-container">
    <div class="popup-form" id="new-group">
        <?php $this->view_partial('groups', 'new-group', $page); ?>
    </div>
</div>

<div id="table-wrapper">
    <?php $this->view_partial( "groups", "table-groups", $data = [] ); ?>
</div>

