<?php

use app\core\Pagination;

// Limit and page number
$limit                 = ( !empty( $limit ) ? $limit : 12 );
$page                  = ( !empty( $data ) ? $data : 1 );
$total_users           = $this->get_all_users()->count();
$users                 = $this->get_all_users_paginated( $limit, $page )->sortBy('name', SORT_NATURAL, false);

$total_users_paginated = $users->count();
$total_rows            = $total_users;

?>

<div class="table-intro">
    <h1>System users table</h1>
    <p>
        Users: <?= $total_users ?>
        <?php
        if( $total_users > $limit ){
            echo '/ On this page: ' . $total_users_paginated ;
        }
        ?>
    </p>
    <div class="table-select-rows">
        <form action="<?= BASE_PATH ?>user/index"
        >
            <input type="text" name="rows" value="<?= $limit ?>">
            <input type="submit" name="rowSubmit" value="set" class="submit-form">
        </form>
    </div>
</div>

<div class="table">
    <div class="table-row">
        <div class="table-header">User</div>
        <div class="table-header">Email</div>
        <div class="table-header">Groups</div>
        <div class="table-header">Roles</div>
        <div class="table-header">Last login</div>
        <div class="table-header">Since</div>
        <div class="table-header"></div>
    </div>
    <div class="table-row"></div>
    <?php
    foreach( $users as $user ){
        echo '<div class="table-row">';
        echo '<div class="table-cell">' . $user->name . '</div>';
        echo '<div class="table-cell">' . $user->email . '</div>';
        echo '<div class="table-cell">';
        /** User groups */
        $total_groups =  $user->groups->count();
        $i = 1;
        foreach( $user->groups as $group ){
            echo $group->name;
            if( $i< $total_groups ){
                echo',&nbsp;';
            }
            $i++;
        }
        echo '</div>';
        echo '<div class="table-cell">';
        /** User roles */
        $total_roles =  $user->roles->count();
        $j = 1;
        foreach( $user->roles as $role ){
            echo $role->name;
            if( $j < $total_roles ){
                echo',&nbsp;';
            }
            $j++;
        }
        echo '</div>';
        /** User last login */
        $user_last_login = !empty( $user->login ) ? $user->login->previous : "";
        echo '<div class="table-cell">' . $user_last_login . '</div>';
        echo '<div class="table-cell">' . $user->created_at . '</div>';
        echo '<div class="table-cell">
                <a href="" 
                   class="popup-form-link" 
                   data-id="edit-' . $user->id . '"
                   title="Edit user ' . $user->name . '"
                   >Edit</a>
                <a href="' . BASE_PATH . 'user/delete" 
                   class="popup-form-link" 
                   data-id="delete-' . $user->id . '" 
                   data-url="' . BASE_PATH . 'user/get_user_table_result"
                   data-text="User ' . $user->name . ' is deleted."
                   title="Delete user ' . $user->name . '"
                   >Delete</a>
              </div>';
        echo '</div>';
        echo '<div class="popup-form-container">';
        echo '<div class="popup-form" id="edit-' . $user->id . '">';
            $this->view_partial('user', 'edit-user', $user);
        echo '</div>';
        echo '<div class="popup-form" id="delete-' . $user->id  . '">';
            $this->view_partial('user', 'delete-user', $user);
        echo '</div>';
        echo '</div>';
    }
    ?>
</div>

<?php
// Show the pagination if total rows is bigger then the limit.

if( $total_rows > $limit ) {
    $data_url = 'user/get_user_table_result';
    echo ( new Pagination( $total_rows, $limit, $page ) )->createPagination( $data_url );
}
?>