<?php

$page = isset( $_GET['page'] ) ? $_GET['page'] : 1;

?>

<div class="container">
    <div class="container-title">Users</div>
    <div class="container-menu">
        <a href="" onclick="goBack()">Go back</a>
        <a href="<?= BASE_PATH ?>user/new" class="popup-form-link" data-id="new-user">New user</a>
    </div>
</div>

<div class="popup-form-container">
    <div class="popup-form" id="new-user">
        <?php $this->view_partial('user', 'new-user', $page); ?>
    </div>
</div>

<div id="table-wrapper">
    <?php $this->view_partial( "user", "table-user", $page ); ?>
</div>
