<form action="<?= BASE_PATH ?>groups/add_group"
      method="post" class="popup-form-form"
      data-url="<?= BASE_PATH ?>groups/get_groups_table_result"
      data-id="new-group">
    <a href="" class="popup-form-close"></a>
    <h1>New system group</h1>
    <fieldset>
        <legend>Please fill in the form below.</legend>
        <input type="hidden" name="success" value="New group successfully added.">
        <input type="hidden" name="error" value="There were problems validating the form.">
        <div class="popup-form-section">
            <label for="full_name">Group name<span></span></label>
            <input type="text" name="full_name" value="" title="Please enter a group name"placeholder="Group name">
        </div>
        <div class="popup-form-section">
            <input type="submit" name="newGroupSubmit" value="Add" class="submit-form">
        </div>
    </fieldset>
</form>

