<?php

$groups = $this->get_all_groups();

?>

<div class="table-intro">
    <h1>System groups table</h1>
    <p>Groups: <?= $groups->count() ?></p>
</div>

<div class="table">
    <div class="table-row">
        <div class="table-header">Group</div>
        <div class="table-header">Users</div>
        <div class="table-header">Since</div>
        <div class="table-header"></div>
    </div>
    <div class="table-row"></div>
    <?php
    foreach( $groups as $group ){
        $total_users = $group->users->count();
        echo '<div class="table-row">';
        echo '<div class="table-cell">' . ' (' . $total_users . ') ' . $group->name . '</div>';
        echo '<div class="table-cell">';
        /** Users */
        if( !$group->users->isEmpty() ) {
            echo '<select>';
            foreach ($group->users as $user) {
                echo '<option>' . $user->name . '</option>';
            }
            echo '</select>';
        } else {
            echo '<i>This group has no users</i>';
        }
        echo '</div>';

        echo '<div class="table-cell">' . $group->created_at . '</div>';
        echo '<div class="table-cell">
                <a href="" class="popup-form-link" 
                   data-id="' . $group->id . '"
                   title="Edit group ' . $group->name . '"
                   >Edit</a>
                <a href="' . BASE_PATH . 'groups/delete" 
                   title="Delete group ' . $group->name . '"
                   class="popup-form-delete" 
                   data-id="' . $group->id . '" 
                   data-text="Group ' . $group->name . ' is deleted."
                   data-url="' . BASE_PATH . 'groups/get_groups_table_result"
                   >Delete</a>
              </div>';
        echo '</div>';
        echo '<div class="popup-form-container">';
        echo '<div class="popup-form" id="' . $group->id . '">';
            $this->view_partial('groups', 'edit-group', $group);
        echo '</div>';
        echo '</div>';
    }
    ?>
</div>