<?php

use app\core\Privileges;
use app\core\EventMessage;

$privileges = ( new Privileges() )->privileges;

?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="">
    <meta name="robots" content="nofollow">
    <meta property="og:title" content="Control Management System">
    <meta property="og:type" content="website">
    <meta property="og:description" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <title>Blueberry</title>
</head>
<body>
<!--<div class="se-pre-con">-->
<!--    <div class="se-pre-con-txt">-->
<!--            <span>-->
<!--                <img src="--><?//= PUBLIC_PATH . 'img/icons/gears.gif?'. uniqid() ?><!--">-->
<!--                <br>-->
<!--                Loading, please wait...-->
<!--            </span>-->
<!--    </div>-->
<!--</div>-->

<div class="header">
    <?php if( !empty( $_SESSION['login'] ) ): ?>
    <div class="header-navigation dropdown">
        <button onclick="menuDropDown()" class="dropbtn"></button>
        <div id="myDropdown" class="dropdown-content">
            <a href="<?= BASE_PATH ?>home/index">Home</a>
            <a href="<?= BASE_PATH ?>projects/index">Projects</a>
            <a href="<?= BASE_PATH ?>manual/index">Manual</a>
            <?php
                foreach( $privileges as $privilege ):
                    if( $privilege === "Administrator" ):
                ?>
                        <a href="<?= BASE_PATH ?>adminPanel/index">Admin Panel</a>
                <?php
                    endif;
                endforeach;
             ?>
            <a href="<?= BASE_PATH ?>contact/index">Contact</a>
        </div>
    </div>
    <?php endif; ?>
    <div class="header-title">Blueberry</div>
    <?php if( !empty( $_SESSION['login'] ) ): ?>
    <div class="header-logout">
        <img class="logout-img" data-alt-src="<?= PUBLIC_PATH . 'img/icons/lock_icon_closed.png'?>" src="<?= PUBLIC_PATH ?>img/icons/lock_icon_open.png">
        <a class="logout" href="<?= BASE_PATH ?>login/logout" title="Click to logout">Logout</a>
    </div>
    <?php endif; ?>
</div>

<?= ( new EventMessage() )->display() ?>

<div class="ajax-success"></div>
<div class="ajax-failed"></div>

